### ISSUE TITLE
Potential plotting (plotframe.m) still fails for most 3D simulations (e.g. dipole)

### ISSUE THREAD

**Issue by mattzett** [gemini3d/mat_gemini#1]
I'm still having to comment this out for it to work with 2017b and 2019b; this is the offending line:

%  plotfun(ymd,UTsec,xg, dat.Phitop,'topside potential \Phi_{top} (V)', ...
%    Phitop_lim, [dat.mlatsrc, dat.mlonsrc], h.f9, Phi_cmap)

**Comment by scivision** [comment]
I think this is no longer an issue. This was all refactored and cleaned up in past months. Also, 2D and 3D plotting are part of CI as well now.
