### ISSUE TITLE
plotframe.m no longer fills default arguments

### ISSUE THREAD

**Issue by mattzett** [gemini3d/mat_gemini#11]
The new plotframe.m API seems to require all arguments, whereas previously (and desirably from standpoint of interactive use) it only needed the simulation location and time (first two) and would fill the others with defaults.

**Comment by scivision** [comment]
https://github.com/gemini3d/mat_gemini/blob/master/%2Bgemini3d/%2Bvis/plotframe.m

if you mean this one the way it's written it looks like it only requires the first two arguments. I don't know that I actually tried this however.

**Comment by scivision** [comment]
This turns out to have needed some reworking. Tests were added as well. Plotframe should be good for external use now.
