### ISSUE TITLE
Updates to gemini3d.setup.model_setup() to accommodate user-defined precipitation and electric field shape functions

### ISSUE THREAD

**Issue by mattzett** [gemini3d/mat_gemini#13]
This is particularly relevant to the arcs examples from gemini-examples where the user needs to be able to define different shaped arcs (precipitation and fields) to test how the ionosphere responds in the different cases.

**Comment by mattzett** [comment]
It seems the way to do this might be to put optional shape functions into the nml input file and then have gemini3d.setup.Efield_BCs.m and gemini3d.setup.precip_BCs.m call these if they are present in the input structure.

**Comment by scivision** [comment]
This was already implemented. The functions all accept arguments "cfg" and "xg" which are configuration and grid.

**Comment by mattzett** [comment]
Thanks, yeah I see this now.  I still may tweak the way Efield and precipitation boundary conditions are handled to make this convenient for one of my projects...

**Comment by mattzett** [comment]
ARCS examples now show how to do this.
