### ISSUE TITLE
Need to have an option to use mat_gemini without git

### ISSUE THREAD

**Issue by mattzett** [gemini3d/mat_gemini#27]
some HPC environments like interactive sessions will disable external networking and git.

**Comment by scivision** [comment]
Yes this is good. CI testing without Internet connection might involve making a [Docker container](https://github.community/t/is-there-a-way-to-run-an-action-step-without-networking/162191/3). However, we can at least test ourselves or as you encounter. 

I can easily separate out the Git operations and will do this promptly. Thanks for bringing this up.

**Comment by scivision** [comment]
I believe this was fixed by [5e4b7aa](https://github.com/gemini3d/mat_gemini/commit/5e4b7aa0136906e0a26276f6cc0b382fbaddd4af)
