### ISSUE TITLE
Need to settle on standard paths for input/output files

### ISSUE THREAD

**Issue by mattzett** [gemini3d/mat_gemini#3]
There is still some confusion in the scripting as to whether grid files are stored in simname/inputs/ or simname/.  We should settle on a standard.

**Comment by mattzett** [comment]
From Steve K:

config_srk.nml  Efield_inputs  initial_conditions.h5  inputs  prec_inputs  simgrid.h5  simsize.h5
srk@booker:~/research/data/gemini$ ./build/gemini.bin ~srk/research/data/Gemini_simulations/arcs_full/inputs/config_srk.nml ~srk/research/data/Gemini_simulations/arcs_full/ 
           1 MPI processes detected
./build/gemini.bin Process:       0 /      0 at 20200429T214638.279
ERROR: file does not exist /home/srk/research/data/Gemini_simulations/arcs_full/inputs/simgrid.dat
ERROR STOP 

Error termination. Backtrace:
#0  0x7f797dccb2ed in ???
#1  0x7f797dccbed5 in ???
#2  0x7f797dcccf86 in ???
#3  0x562e8e1030e9 in __pathlib_MOD_assert_file_exists
	at /home/srk/research/data/gemini/src/io/pathlib.f90:48
#4  0x562e8e0274ec in initial_config
	at /home/srk/research/data/gemini/src/gemini.f90:355
#5  0x562e8e0274ec in gemini3d
	at /home/srk/research/data/gemini/src/gemini.f90:80
#6  0x562e8e02351e in main
	at /home/srk/research/data/gemini/src/gemini.f90:5
srk@booker:~/research/data/gemini$

**Comment by scivision** [comment]
this was fixed as part of disambiguation, where config.nml are specified as absolute paths or relative to simulation top directory
