### ISSUE TITLE
model_setup.m does not honor paths in config.nml files

### ISSUE THREAD

**Issue by mattzett** [gemini3d/mat_gemini#6]
This appears to mostly be and issue with the precipitation input files; I haven't noticed any problem with electric field inputs...

**Comment by scivision** [comment]
There was an issue with hard-coded paths. I think this was fixed recently but I'll check.

**Comment by scivision** [comment]
this was fixed as part of the disambiguations work, where config.nml may specify absolute or paths relative to the simulation top directory
